version: "3.8"

services:
  app:
    build: ./app
    ports:
      - 8080:80
    environment:
      PORT: 80
      DB_SOCKET_DIR: /var/run/mysqld
      MYSQL_DATABASE: sample
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./secrets:/secrets
      - dbsocket:/var/run/mysqld # mysqldソケットファイルディレクトリを共有

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/conf/:/etc/mysql/conf.d
      - dbsocket:/var/run/mysqld # mysqldソケットファイルディレクトリを共有
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

volumes:
  dbsocket: # 共通ボリュームを作成
  